application: fbvideo-download 
version: 2
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /main.php
  script: main.php

- url: /co.php
  script: co.php

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.(ico|jpg|png|gif))$
  static_files: static/\1
  upload: static/.*\.(ico|jpg|png|gif)$

- url: /
  script: index.php

- url: /private.php
  script: private.php

- url: /test.php
  script: test.php

- url: /index.php
  script: index.php